[workspace]
members = [
    "crates/gla_core",
    "crates/atlas",
    "crates/tile_key",
    "crates/gla_color",
    "crates/gla_image",
    "crates/gla_command_core",
    "crates/gla_ir",
    "crates/gla_renderer",
    "crates/gla_image_command",
    "crates/gla_doc",
    "crates/gla_storage",
    "crates/gla_session",
]

resolver = "3"
