[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
atlas = { path = "../atlas" }
brush = { path = "../brush" }
gla_doc_renderer = { path = "../gla_doc_renderer" }
gla_document = { path = "../gla_document" }
gla_image = { path = "../gla_image" }
glaphica_core = { package = "core", path = "../core" }
renderer = { path = "../renderer" }
ui = { path = "../ui" }
slotmap = "1"
wgpu = "28.0.0"
winit = "0.30.13"
pollster = "0.4.0"
puffin = "0.20.0"
puffin_http = "0.17.0"
